import { createOdooIcon } from "@/components/OdooIcon";

import crm from "@/assets/odoo/crm.svg.asset.json";
import massMailing from "@/assets/odoo/mass_mailing.svg.asset.json";
import saleManagement from "@/assets/odoo/sale_management.svg.asset.json";
import spreadsheetDashboard from "@/assets/odoo/spreadsheet_dashboard.svg.asset.json";
import stock from "@/assets/odoo/stock.svg.asset.json";
import stockBarcode from "@/assets/odoo/stock_barcode.svg.asset.json";
import qualityControl from "@/assets/odoo/quality_control.svg.asset.json";
import accountAccountant from "@/assets/odoo/account_accountant.svg.asset.json";
import account from "@/assets/odoo/account.svg.asset.json";
import accountBatchPayment from "@/assets/odoo/account_batch_payment.svg.asset.json";
import payment from "@/assets/odoo/payment.svg.asset.json";
import hrHolidays from "@/assets/odoo/hr_holidays.svg.asset.json";
import hrPayroll from "@/assets/odoo/hr_payroll.svg.asset.json";
import hrAttendance from "@/assets/odoo/hr_attendance.svg.asset.json";
import hrRecruitment from "@/assets/odoo/hr_recruitment.svg.asset.json";
import mrp from "@/assets/odoo/mrp.svg.asset.json";
import mrpPlm from "@/assets/odoo/mrp_plm.svg.asset.json";
import mrpMaintenance from "@/assets/odoo/mrp_maintenance.svg.asset.json";
import website from "@/assets/odoo/website.svg.asset.json";
import marketingAutomation from "@/assets/odoo/marketing_automation.svg.asset.json";
import fleet from "@/assets/odoo/fleet.svg.asset.json";
import planning from "@/assets/odoo/planning.svg.asset.json";
import hr from "@/assets/odoo/hr.svg.asset.json";
import project from "@/assets/odoo/project.svg.asset.json";

export const OdooCrm = createOdooIcon(crm.url, "Odoo CRM");
export const OdooMassMailing = createOdooIcon(massMailing.url, "Odoo Email Marketing");
export const OdooSale = createOdooIcon(saleManagement.url, "Odoo Sales");
export const OdooSpreadsheetDashboard = createOdooIcon(spreadsheetDashboard.url, "Odoo Dashboards");
export const OdooStock = createOdooIcon(stock.url, "Odoo Inventory");
export const OdooStockBarcode = createOdooIcon(stockBarcode.url, "Odoo Barcode");
export const OdooQualityControl = createOdooIcon(qualityControl.url, "Odoo Quality");
export const OdooAccountant = createOdooIcon(accountAccountant.url, "Odoo Accounting");
export const OdooAccount = createOdooIcon(account.url, "Odoo Invoicing");
export const OdooBatchPayment = createOdooIcon(accountBatchPayment.url, "Odoo Batch Payment");
export const OdooPayment = createOdooIcon(payment.url, "Odoo Payment");
export const OdooHolidays = createOdooIcon(hrHolidays.url, "Odoo Time Off");
export const OdooPayroll = createOdooIcon(hrPayroll.url, "Odoo Payroll");
export const OdooAttendance = createOdooIcon(hrAttendance.url, "Odoo Attendance");
export const OdooRecruitment = createOdooIcon(hrRecruitment.url, "Odoo Recruitment");
export const OdooMrp = createOdooIcon(mrp.url, "Odoo Manufacturing");
export const OdooMrpPlm = createOdooIcon(mrpPlm.url, "Odoo PLM");
export const OdooMrpMaintenance = createOdooIcon(mrpMaintenance.url, "Odoo Maintenance");
export const OdooWebsite = createOdooIcon(website.url, "Odoo Website");
export const OdooMarketingAutomation = createOdooIcon(marketingAutomation.url, "Odoo Marketing Automation");
export const OdooFleet = createOdooIcon(fleet.url, "Odoo Fleet");
export const OdooPlanning = createOdooIcon(planning.url, "Odoo Planning");
export const OdooHr = createOdooIcon(hr.url, "Odoo Employees");
export const OdooProject = createOdooIcon(project.url, "Odoo Project");